version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/home/nginx
    env_file:
      - .env
    depends_on:
      - node
    command: sh -c /home/nginx/nginx.sh
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

  node:
    image: nodejs:alpine
    ports:
      - "9001:8000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
