version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/home/nginx
    env_file:
      - .env
    depends_on:
      - node
    command: sh -c /home/nginx/nginx.sh
    logging:
      options:
        max-size: 1g

  node:
    image: nodejs:alpine
    ports:
      - "9001:8000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    restart: unless-stopped
    volumes:
      # Mount the code for hot reloading
      - .:/usr/src/app
    logging:
      options:
        max-size: 1g

  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:release
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs api
      - "8080:8080" # ipfs gateway
    volumes:
      - ./compose/ipfs:/data/ipfs
    logging:
      options:
        max-size: 500m
