version: "3.5"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/home/nginx
    env_file:
      - .env
    depends_on:
      - node
    command: sh -c /home/nginx/nginx.sh
    logging:
      options:
        max-size: 1g

  node:
    image: nodejs:alpine
    ports:
      - "9001:8000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    mem_limit: 3g
    restart: unless-stopped
    volumes:
      # Mount the code for hot reloading
      - .:/usr/src/app
    logging:
      options:
        max-size: 1g

networks:
  default:
    name: general_admission
