version: "3.5"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx:/home/nginx
    env_file:
      - .env
    depends_on:
      - node
    command: sh -c /home/nginx/nginx.sh
    logging:
      options:
        max-size: 1g

  node:
    image: nodejs:alpine
    ports:
      - "9001:8000"
    build:
      context: ./ga
      dockerfile: ./ga/Dockerfile
    container_name: node
    mem_limit: 3g
    restart: unless-stopped
    logging:
      options:
        max-size: 1g
    
  social:
    container_name: social
    ports:
      - "8001:8001"
    build:
      context: ./social
      dockerfile: ./social/Dockerfile
    restart: unless-stopped
    logging:
      options:
        max-size: 1g

networks:
  default:
    name: general_admission
