version: 2.1

jobs:
  init:
    working_directory: ~/general-admission
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-

      - run: rm -rf /home/circleci/audius-dapp/node_modules/websocket/.git

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm run lint
      - run: npm run tsc
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  test-production:
    working_directory: ~/general-admission
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: run test
          command: npm run test:prod

workflows:
  version: 2
  test:
    jobs:
      - init
      - test-production:
          requires:
            - init

  production:
    triggers:
      - schedule:
          cron: "0,6,12,18,24,30,36,42,48,54 * * * * "
          filters:
            branches:
              only:
                - master
    jobs:
      - init
      - test-production:
          requires:
            - init