export const DEFAULT_IMAGE_URL =
  'https://download.audius.co/static-resources/preview-image.jpg'
export const AUDIO_REWARDS_IMAGE_URL =
  'https://download.audius.co/static-resources/audio-rewards.png'
export const SIGNUP_REF_IMAGE_URL =
  'https://download.audius.co/static-resources/signup_referral.png'
export const USER_NODE_IPFS_GATEWAY = 'https://usermetadata.audius.co/ipfs/'

// App routes that should not be treated as user handles
export const APP_ROUTES = [
  'download',
  'upload',
  'explore',
  'trending',
  'check',
  'undefined',
  'press',
  'audio',
  'signup',
  'error',
  'health_check',
  'proxy',
  'social',
  'apple-app-site-association',
  '204',
  'feed',
  'favorites',
  'library',
  'history',
  'dashboard',
  'rewards',
  'airdrop',
  'wallet',
  'settings',
  'signin',
  'login',
  'join',
  'signon',
  'register',
  'oauth',
  'notifications',
  'app-redirect',
  'deactivate',
  'messages',
  'payments',
  'dev-tools',
  'search',
  '404',
  'empty_page',
  'genres',
  'legal',
  'auth-redirect',
  'reposting_users',
  'favoriting_users',
  'following',
  'followers',
  'supporting',
  'top-supporters',
  'account',
  'verification',
  'about',
  'change-email',
  'change-password',
  'authorized-apps',
  'label-account',
  'managing-you',
  'accounts-you-manage',
  'export-private-key',
  'transaction-history',
  'coins',
  'solana',
  'user-id-parser',
  'coin-api-mocks',
  'create-email',
  'create-password',
  'create-login-details',
  'pick-handle',
  'review-handle',
  'finish-profile',
  'select-genres',
  'select-artists',
  'loading',
  'app-cta',
  'completed',
  'completed-referrer',
] as readonly string[]
