version: "3.5"

services:
  social:
    container_name: social
    ports:
      - "8001:8001"
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      # Mount the code for hot reloading
      - ./:/home/node/app
      # Do not mount node modules or build folder
      - /home/node/app/dist/
      - /home/node/app/node_modules/
    logging:
      options:
        max-size: 1g

networks:
  default:
    name: general_admission